build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test
    - curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar xzv -C /tmp
    - /tmp/bats-0.4.0/install.sh /usr/local
    - bats e2e/*.bats

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-s3
    when:
      branch: master

plugin:
  name: S3
  desc: Publish files and artifacts to Amazon S3
  type: publish
  image: plugins/drone-s3
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
